data:
  tokenizer_path: "./models/gpt-clean-16000.json"
  train_path: "./data/babylm_100M_clean"
  eval_path: "./data/babylm_dev_clean"
  seq_length: 128
  eval_samples: 16384

model:
  type: "Llama" # or "GPT2"
  name: "Llama-97M-strict"
  hidden_size: 768
  intermediate_size: 2048 # 2/3 * 4 * hidden_size as in the paper
  n_layer: 12
  n_head: 12 
  tie_word_embeddings: True # Tie word embeddings to match GPT2 size

training:
  lr: 7e-4
  batch_size: 128
  num_epochs: 6 # epochs is not enough to reach Llama eval loss
  gradient_accumulation_steps: 2
  warmup_steps: 300
  fp16: True

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "./models/"

